version: "3.9"
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=zootable
      - POSTGRES_USER=zootable
      - POSTGRES_PASSWORD=zootable
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    image: zootable
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      - db

volumes:
  postgres_data:
