# fly.toml app configuration file generated for na-zootable on 2023-05-26T00:17:18-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "na-zootable"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
PORT = "8080"
DJANGO_ALLOWED_HOSTS = "127.0.0.1 .fly.dev .zootable.com"
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
SECURE_HSTS_SECONDS = "31536000"
PROXY_SSL_HEADER = "1"

[build]
dockerfile = "dockerfile"

[experimental]
auto_rollback = true

[[vm]]
size = "shared-cpu-2x"
memory = "512mb"

[[services]]
internal_port = 8080
processes = ["app"]
protocol = "tcp"

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
handlers = ["http"]
port = 80
force_https = true

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"
