name: Backup database

on:
  push:
  schedule:
    - cron: "17 3 * * *" # daily
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  PGPASSWORD: ${{ secrets.PGPASSWORD }}

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Get flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: dump the database
        run: |
          flyctl proxy 5432:5432 -a zootable-na-db &
          docker run --rm --network host \
            -v $(pwd):$(pwd) \
            -w $(pwd) \
            -e PGPASSWORD=$PGPASSWORD \
            postgres:14-alpine \
            pg_dump -Fc -h localhost -U na_zootable zootable > zootable.dump
          du -h zootable.dump
          ls -lah
          kill %1
