name: Build and Test

on: [push]

env:
  SECRET_KEY: secret_key_github_actions_12345_github_action_secret_key
  SECURE_SSL_REDIRECT: 0

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: zootable
          POSTGRES_PASSWORD: zootable
          POSTGRES_DB: zootable
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --mount type=tmpfs,destination=/var/lib/postgresql/data --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -e .[test]
      - name: Run migrations
        run: python manage.py migrate --noinput
      - name: Test with pytest
        run: |
          pytest --cov=zoo_checks --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
